#!/bin/bash

# List files from GitHub repositories

# GitHub API documentation:
# https://docs.github.com/en/rest/guides/getting-started-with-the-rest-api
# https://docs.github.com/en/rest/git/trees

# GitHub API headers for `gh api`
headers=(
    -H "Accept: application/vnd.github+json"
    -H "X-GitHub-Api-Version: 2022-11-28"
)

# List all my repositories as nameWithOwner (owner/repo) one per line.
get_my_repos() {
    gh repo list --json nameWithOwner --jq '.[].nameWithOwner'
    # gh api "${headers[@]}" '/user/repos?per_page=100' --jq '.[].full_name'
}

# Get the default branch of a repository given as owner/repo.
get_repo_default_branch() {
    gh api "${headers[@]}" "/repos/$1" --jq '.default_branch'
}

# List files from a repository given as owner/repo one file path per line.
# Arguments:
#   $1: owner/repo
#   $2: branch (default: default branch of the repository)
# Note: If no tree is returned, the returned text does not end with a newline.
list_repo_files() {
    if test -n "$2" ; then
        branch="$2"
    else
        branch="$(get_repo_default_branch "$1")"
    fi
    gh api "${headers[@]}" \
        "/repos/$1/git/trees/$branch?recursive=true" --jq '.tree[].path'
}

# List files from all my repositories.
for name_with_owner in $(get_my_repos) ; do
    printf '### %s\n' "$name_with_owner"
    list_repo_files "$name_with_owner"
    printf '\n'
done
