#!/bin/bash

# textpack

# Create a compressed tar archive of the current directory, given file or directory
# and encode it to text.
# The archive can be extracted using `base64 -d | tar -xJf -`

# The aim is to be able to move the directory content over text-only channels.

# TODO:
# - Allow to specify multiple targets (files or directories) to pack.
# - Add VSC ignores.
# - Support compression algorithm selection (xz not on Gaia R81.20).


# --- The compression options for tar:
# Higher xz compression:
compress_option='-Ixz -8 -e'
# Standard xz compression:
# compress_option='-J'
# Standard gzip compression:
# compress_option='-z'

# Decoding from text and extracting the content:
extract_command="base64 -d | tar -xJf -"
test_extract_command="base64 -d | tar -tJf -"
# extract_command="python3 -c 'import base64, sys; sys.stdout.buffer.write(base64.a85decode(sys.stdin.buffer.read()))' | tar -xJf -"
# extract_command="base64 -d | tar -xzf -"
# test_extract_command="base64 -d | tar -tzf -"

extract_comment="Press Ctrl+d at the end."


# Show usage information
usage() {
    cat <<EOF
Create a compressed tar archive of the current directory, given file or directory
and encode it to text. The archive can be extracted using '$extract_command'
The aim is to be able to copy the arbitrary content over text clipboard, terminals
and other text-only channels.

Usage: $(basename "$0") [-tceLh] [-x exclude_list_name] [target]

target: the file or directory to pack (default: \$(pwd))
    The target name will be included in the archive, so it will be created when
    extracting. To pack just the current directory content, use '.' as the target.

Options:
  -t  Test mode: create the tar and immediately list its contents
  -c  Clipboard mode: put the encoded tar in the clipboard (WSL or Windows only)
  -e  Include extract command in the output (for copy-paste convenience)
  -L  Follow symlinks: include the content of the linked files instead of the links themselves
  -x  Exclude list(s): specify one or more exclude list names (default is built-in 'default' list)
      The exclude list(s) can be defined in files named .textpack_exclude_<name>
      Use 'none' to disable the default exclude list.
  -h  Show this help message
EOF
}


exclude_list_names=()

while getopts "thceLx:" opt ; do
    case $opt in
        t)
            # test mode: create a tar and immediately list its contents
            test_mode=1
            ;;
        c)
            # clipboard mode: create a tar and copy it to the clipboard
            clipboard_mode=1
            ;;
        e)
            # include extract command in the output
            include_extract_command=1
            ;;
        L)
            # follow symlinks
            follow_symlinks=1
            ;;
        x)
            # exclude list(s)
            exclude_list_names+=("$OPTARG")
            ;;
        h)
            # help mode: show usage information
            usage
            exit 0
            ;;
        *)
            echo "Unknown option: -$opt" >&2
            usage
            exit 1
            ;;
    esac
done
shift $((OPTIND - 1))

if [ "$#" -eq 1 ] ; then
    target="$1"
elif [ "$#" -eq 0 ] ; then
    target="$(pwd)"
else
    echo "See $0 -h for usage. Unexpected number of arguments: $#" >&2
    exit 1
fi

target_base=$(basename "$target")
dir_base=$(dirname "$target")

if [ ${#exclude_list_names[@]} -eq 0 ] ; then
    exclude_list_names+=("default")
elif [ "${exclude_list_names[0]}" = "none" ] ; then
    exclude_list_names=()
fi

exclude_list=
for exclude_list_name in "${exclude_list_names[@]}" ; do
    if [ "$exclude_list_name" = "default" ] ; then
        exclude_list=$(cat <<EOF
__pycache__
*.egg-info
$target_base/.git
$target_base/.vscode
$target_base/.github
$target_base/.venv
$target_base/.pytest_cache
$target_base/build
$target_base/tmp
EOF
)
    else
        # TODO Define directory/directories for exclude list files.
        exclude_list_file="$dir_base/.textpack_exclude_$exclude_list_name"
        if [ -f "$exclude_list_file" ] && [ -r "$exclude_list_file" ] ; then
            exclude_list+=$(sed 's/^{{{}}}/'"$target_base"/ "$exclude_list_file")
            exclude_list+=$'\n'
        else
            echo "Exclude list file $exclude_list_file not found or not readable." >&2
        fi
    fi
done


encode () {
    base64
    # python3 -c "import base64, sys; sys.stdout.write(base64.a85encode(sys.stdin.buffer.read()).decode('ascii'))"
}


postprocess () {
    if [ "$test_mode" = 1 ] ; then
        tee >(wc -c > "$tmp_len_counter") |
        eval "$test_extract_command" || {
            echo "Failed to extract the tar archive." >&2
            exit 1
        }
    else
        {
            if [ "$include_extract_command" = 1 ] ; then
                printf "%s  # %s\n" "$extract_command" "$extract_comment"
            fi
            cat
        } | 
        tee >(wc -c > "$tmp_len_counter") |
        {
            if [ "$clipboard_mode" = 1 ] && grep -qi 'wsl2' /proc/version >/dev/null 2>&1 ; then
                clip.exe
            else
                cat
            fi
        }
    fi
}


if [ ! -d "$dir_base" ] || [ ! -r "$dir_base" ] ; then
    echo "Directory $dir_base does not exist or is not readable." >&2
    exit 1
fi

cd "$dir_base" || {
    printf 'Failed to change directory to %s.\n' "$dir_base" >&2
    exit 1
}

tmp_len_counter=$(mktemp)
trap 'rm -f "$tmp_len_counter"' EXIT

tar_options=
if [ "$follow_symlinks" = 1 ] ; then
    tar_options='-h'
fi

# TODO: --exclude-vcs-ignores is not supported on Gaia R81.20
#   replace it with entries in the exclude list
tar -c "$compress_option" $tar_options -f- \
        --exclude-from <(printf "%s\n" "$exclude_list") "$target_base" |
    encode |
    tmp_len_counter="$tmp_len_counter" postprocess

printf '\n====== Length of the encoded output: %s bytes ======\n' "$(cat "$tmp_len_counter")" >&2
